#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: fbbd4e3
#
Name     : R-SuppDists
Version  : 1.1.9.9
Release  : 53
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/SuppDists_1.1-9.9.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/SuppDists_1.1-9.9.tar.gz
Summary  : Supplementary Distributions
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-SuppDists-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Inverse Gauss, Kruskal-Wallis, Kendall's Tau, Friedman's chi
  squared, Spearman's rho, maximum F ratio, the Pearson product
  moment correlation coefficient, Johnson distributions, normal
  scores and generalized hypergeometric distributions.

%package lib
Summary: lib components for the R-SuppDists package.
Group: Libraries

%description lib
lib components for the R-SuppDists package.


%prep
%setup -q -n SuppDists
pushd ..
cp -a SuppDists buildavx2
popd
pushd ..
cp -a SuppDists buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1742840739

%install
export SOURCE_DATE_EPOCH=1742840739
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/SuppDists/DESCRIPTION
/usr/lib64/R/library/SuppDists/INDEX
/usr/lib64/R/library/SuppDists/Meta/Rd.rds
/usr/lib64/R/library/SuppDists/Meta/features.rds
/usr/lib64/R/library/SuppDists/Meta/hsearch.rds
/usr/lib64/R/library/SuppDists/Meta/links.rds
/usr/lib64/R/library/SuppDists/Meta/nsInfo.rds
/usr/lib64/R/library/SuppDists/Meta/package.rds
/usr/lib64/R/library/SuppDists/NAMESPACE
/usr/lib64/R/library/SuppDists/NEWS.Rd
/usr/lib64/R/library/SuppDists/R/SuppDists
/usr/lib64/R/library/SuppDists/R/SuppDists.rdb
/usr/lib64/R/library/SuppDists/R/SuppDists.rdx
/usr/lib64/R/library/SuppDists/help/AnIndex
/usr/lib64/R/library/SuppDists/help/SuppDists.rdb
/usr/lib64/R/library/SuppDists/help/SuppDists.rdx
/usr/lib64/R/library/SuppDists/help/aliases.rds
/usr/lib64/R/library/SuppDists/help/paths.rds
/usr/lib64/R/library/SuppDists/html/00Index.html
/usr/lib64/R/library/SuppDists/html/R.css

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/SuppDists/libs/SuppDists.so
/V4/usr/lib64/R/library/SuppDists/libs/SuppDists.so
/usr/lib64/R/library/SuppDists/libs/SuppDists.so
